import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1a1f2f",
        "secondary-container": "#00a572",
        "surface-container-low": "#161b2b",
        "surface-container-high": "#25293a",
        "tertiary-container": "#ca8100",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#472a00",
        "on-secondary-container": "#00311f",
        "secondary": "#4edea3",
        "outline-variant": "#464554",
        "on-tertiary-container": "#3e2400",
        "on-secondary-fixed": "#002113",
        "on-surface": "#dee1f7",
        "surface-container-lowest": "#090e1c",
        "surface-dim": "#0e1322",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#dee1f7",
        "tertiary-fixed-dim": "#ffb95f",
        "surface": "#0e1322",
        "primary-fixed-dim": "#c0c1ff",
        "error-container": "#93000a",
        "on-secondary": "#003824",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary": "#1000a9",
        "on-error": "#690005",
        "on-background": "#dee1f7",
        "primary": "#c0c1ff",
        "on-primary-container": "#0d0096",
        "secondary-fixed-dim": "#4edea3",
        "background": "#0e1322",
        "surface-tint": "#c0c1ff",
        "inverse-primary": "#494bd6",
        "primary-container": "#8083ff",
        "error": "#ffb4ab",
        "outline": "#908fa0",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed": "#07006c",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#343949",
        "primary-fixed": "#e1e0ff",
        "inverse-on-surface": "#2b3040",
        "tertiary": "#ffb95f",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#2f3445",
        "surface-variant": "#2f3445"
      },
      fontFamily: {
        "headline": ["var(--font-inter)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
        "mono": ["var(--font-jetbrains-mono)", "monospace"]
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
